"""Packaged discovery metadata; no runtime dependency on the research archive."""

ECONOMIC_METHODS = (
    (
        "economic_normal_form",
        "NormalFormGame",
        "https://timroughgarden.org/f13/f13.html",
        "implemented_core",
        "Small local strategic interactions",
        "Known payoff tensors; finite legal actions",
    ),
    (
        "economic_repeated_games",
        "RepeatedGame",
        "https://arxiv.org/abs/1908.09453",
        "implemented_core",
        "Repeated evidence sharing",
        "Continuation and observation noise explicitly modeled",
    ),
    (
        "economic_public_goods",
        "HypergraphPublicGoods",
        "https://arxiv.org/abs/2001.10313",
        "implemented_core",
        "Shared evidence and costly verification",
        "State contribution budget per agent versus per edge",
    ),
    (
        "economic_threshold_coalitions",
        "ThresholdTeamGame",
        "https://arxiv.org/abs/2001.10313",
        "numpy_adaptation",
        "Complementary specialist teams",
        "Our nonlinear task adaptation; no generic stability theorem",
    ),
    (
        "economic_contract_net",
        "ContractNet",
        "https://doi.org/10.1109/TC.1980.1675516",
        "implemented_core",
        "Distributed task procurement",
        "Task-sharing protocol; not inherently truthful",
    ),
    (
        "economic_single_item_auctions",
        "FirstPriceAuction",
        "https://timroughgarden.org/f13/f13.html",
        "implemented_core",
        "Allocate tools or procure work",
        "State private-value utility, budgets, reserves and tie rules",
    ),
    (
        "economic_combinatorial_vcg",
        "CombinatorialAuction",
        "https://arxiv.org/abs/1607.07684",
        "implemented_core",
        "Allocate complementary resource bundles",
        "Truthfulness requires suitable exact allocation and utility assumptions",
    ),
    (
        "economic_double_auction",
        "DoubleAuction",
        "https://arxiv.org/abs/2609.02580",
        "implemented_core",
        "Exchange resource allocations",
        "Explicit clearing and inventories; no automatic truthfulness",
    ),
    (
        "economic_congestion",
        "CongestionGame",
        "https://timroughgarden.org/f13/f13.html",
        "implemented_core",
        "Route work across shared tools",
        "Exact-potential guarantees require the corresponding game assumptions",
    ),
    (
        "economic_stable_matching",
        "DeferredAcceptance",
        "https://doi.org/10.2307/2312726",
        "implemented_core",
        "Match agents and projects",
        "Classical preference domain; arbitrary complementary teams excluded",
    ),
    (
        "economic_bargaining",
        "AlternatingOffers",
        "https://doi.org/10.2307/1907266",
        "implemented_core",
        "Negotiate deadline quality and price",
        "Nash solution separate from dialogue; disagreement utility explicit",
    ),
    (
        "economic_coalition_value",
        "ShapleyEstimator",
        "https://doi.org/10.1007/BF01787031",
        "implemented_core",
        "Share rewards for joint artifacts",
        "Normalized characteristic value; exact permutation limit 9; sampled estimates include standard errors; graph restriction extends to fully contained hyperedges",
    ),
    (
        "economic_prediction_market",
        "LMSRMarket",
        "https://mason.gmu.edu/~rhanson/mktscore.pdf",
        "implemented_core",
        "Forecast independent verification outcomes",
        "Outcome oracle, liquidity and subsidy required; strategic traders can influence prices",
    ),
    (
        "economic_external_regret",
        "ExternalRegretPolicy",
        "https://timroughgarden.org/f13/f13.html",
        "implemented_core",
        "Adaptive bidding and routing",
        "Bounded payoff feedback; empirical CCE connection, not generic Nash",
    ),
    (
        "economic_internal_regret",
        "InternalRegretPolicy",
        "https://ma.huji.ac.il/~hart/abs/adapt.html",
        "implemented_core",
        "Coordinated local recommendations",
        "Distinguish internal deviations from fixed action deviations",
    ),
    (
        "economic_cfr",
        "OpenSpielCFR",
        "https://arxiv.org/abs/1908.09453",
        "optional_adapter",
        "Small imperfect-information economic games",
        "Classical Nash guarantee for appropriate two-player zero-sum perfect-recall games",
    ),
    (
        "economic_psro",
        "PolicySpaceResponseOracles",
        "https://arxiv.org/abs/1711.00832",
        "numpy_adaptation",
        "Maintain diverse strategic agents",
        "Approximate LLM response oracle; restricted population equilibria",
    ),
    (
        "economic_alpharank",
        "AlphaRankEvaluator",
        "https://arxiv.org/abs/1903.01373",
        "implemented_core",
        "Evaluate cyclic strategy populations",
        "Ranking is neither Nash certificate nor welfare optimization",
    ),
    (
        "economic_opponent_shaping",
        "LOLAAdapter",
        "https://arxiv.org/abs/1709.04326",
        "numpy_adaptation",
        "Learn reciprocal behavior",
        "Requires learning model and gradient access for fidelity",
    ),
    (
        "economic_mean_field",
        "MultiTypeMeanField",
        "https://arxiv.org/abs/1802.05438",
        "numpy_adaptation",
        "Scale populations with roles",
        "Averages may erase sparse complementarities",
    ),
    (
        "economic_learned_auctions",
        "LearnedAuction",
        "https://arxiv.org/abs/1706.03459",
        "numpy_adaptation",
        "Optimize allocation and payment",
        "Empirical deviation search is not exact DSIC",
    ),
    (
        "economic_learned_institutions",
        "TwoLevelInstitution",
        "https://arxiv.org/abs/2108.02755",
        "callback_training",
        "Learn incentives while workers adapt",
        "Simulation-specific; changing rules changes the game",
    ),
    (
        "economic_other_regarding_q",
        "GroupHistoryQPolicy",
        "https://arxiv.org/abs/2410.10921",
        "numpy_adaptation",
        "Condition cooperation on group history",
        "Other-regarding state is not necessarily altruistic utility",
    ),
    (
        "economic_language_self_play",
        "NegotiationSelfPlay",
        "https://arxiv.org/abs/1706.05125",
        "callback_training",
        "Improve structured language offers",
        "Validate structured outcomes and hold out partners",
    ),
    (
        "economic_information_design",
        "FramingAndDisclosurePolicy",
        "https://arxiv.org/abs/2509.25565",
        "numpy_adaptation",
        "Study evidence framing and disclosure",
        "Belief oracle is a modeling assumption; no general behavior guarantee",
    ),
    (
        "economic_leader_follower",
        "StackelbergContractGame",
        "https://arxiv.org/abs/2108.02755",
        "numpy_adaptation",
        "Model scheduler incentives and worker effort",
        "Tentative extension; full principal-agent literature not covered",
    ),
)
